# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
# joint_limits:
#   right_arm_0_joint:
#     has_velocity_limits: true
#     max_velocity: 0.24
#     has_acceleration_limits: false
#     max_acceleration: 0
#   right_arm_1_joint:
#     has_velocity_limits: true
#     max_velocity: 0.24
#     has_acceleration_limits: false
#     max_acceleration: 0
#   right_arm_2_joint:
#     has_velocity_limits: true
#     max_velocity: 0.5
#     has_acceleration_limits: false
#     max_acceleration: 0
#   right_arm_3_joint:
#     has_velocity_limits: true
#     max_velocity: 0.5
#     has_acceleration_limits: false
#     max_acceleration: 0
#   right_arm_4_joint:
#     has_velocity_limits: true
#     max_velocity: 0.5
#     has_acceleration_limits: false
#     max_acceleration: 0
#   right_arm_5_joint:
#     has_velocity_limits: true
#     max_velocity: 0.8
#     has_acceleration_limits: false
#     max_acceleration: 0
#   right_arm_6_joint:
#     has_velocity_limits: true
#     max_velocity: 0.8
#     has_acceleration_limits: false
#     max_acceleration: 0
joint_limits:
  right_arm_0_joint:
    has_velocity_limits: true
    max_velocity: 0.90
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_1_joint:
    has_velocity_limits: true
    max_velocity: 0.90
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_2_joint:
    has_velocity_limits: true
    max_velocity: 0.9
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_3_joint:
    has_velocity_limits: true
    max_velocity: 0.9
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_4_joint:
    has_velocity_limits: true
    max_velocity: 0.9
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_5_joint:
    has_velocity_limits: true
    max_velocity: 0.9
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_6_joint:
    has_velocity_limits: true
    max_velocity: 0.9
    has_acceleration_limits: false
    max_acceleration: 0